### ISSUE TITLE
QMK's "Permissive Hold" Tap / Hold

### ISSUE THREAD

**Issue by sungkang** [KinesisCorporation/SmartSetApps#14]
having the ability for a key interrupt to treat the dual-role key that is held down to be registered as the held key even if the tapping term has not been exceeded would be a great feature that would solve most of my issues with the current tap/hold implementation of this firmware.

I rely on this feature to quickly jump through various buffers and tabs and it's jarring to wait for the full term to where it's almost unusable.

so i currently end up just mapping it to capslock and use karabiner (for macos) to intercept the key and implement the tap/hold behavior. Though it's software, it's plenty responsive enough to where I don't notice it.
But it would be nice to simply have that mapped in the firmware so that I am not coupled to the software on a single particular machine.

**Comment by sungkang** [comment]
https://docs.qmk.fm/#/tap_hold
for reference.

**Comment by KinesisCorporation** [comment]
Hi Sung, thanks for this suggestion. We'll pass this along to our engineers to evaluate, but can't make any promises.

FWIW- This is a really a firmware feature and not an App feature (the App is just a GUI for reading/writing to the underlying text file). Which SmartSet keyboard are you using?

**Comment by sungkang** [comment]
where is the more appropriate place to post issues regarding the firmware?

**Comment by KinesisCorporation** [comment]
Best to submit feature requests directly to us via this form and we'll route them appropriately. Thanks!

https://kinesis-ergo.com/support/contact-a-technician/

**Comment by phchang** [comment]
I am having this issue as well with the tap/hold, and use Karabiner instead of using the firmware feature. This would be a great improvement to the Advantage 360.
