### ISSUE TITLE
error when trying to build the adv2 project

### ISSUE THREAD

**Issue by louyo** [KinesisCorporation/SmartSetApps#16]
"can't find u_form_main"
Not in the source files.
Any other source of the project files?

Also don't see a project file for the 360 in the 360 folder.
Not sure about "Linux users can just use the source on Github"..

Lou

**Comment by KinesisCorporation** [comment]
We are deprecating the current Adv2 app and in the process of integrating that functionality into a separate dashboard of the newer Advantage360 App.. So unfortunately this is a dead end. We will update the link on our website now. Sorry for the confusion but we will release the new files here later this year.

https://github.com/KinesisCorporation/SmartSetApps/tree/master/SmartSetAdv360

**Comment by louyo** [comment]
Thanks. Please make sure that all the source files needed to build for Linux are included.
